<a href="https://colab.research.google.com/github/maleahjamieson/machine_learning/blob/master/HW_4/HW4_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Problem One

In [0]:
import numpy as np

Defining error messages:

In [0]:
class Error(Exception):
  """baseline for other errors"""

# matrix is not square
class NotSquare(Error):
  def __init__(self, message):
    self.message = "ERROR:" + message + " is not square."

# kernel is too big
class KernelTooLarge(Error):
  def __init__(self, message):
    self.message = message

Function to check if a matrix is square:

In [0]:
def square(matrix):
  for m in matrix:
      if len(m) != len(matrix):
        return False
  return True

Using only `numpy`, implement the function `conv2d`. It takes as input `input_mat` and `kernel_mat` and outputs `output_mat`. All variables are **square** matrices. It should compute the convolution of `input_mat` with the kernel `kernel_mat` using **valid padding**.

Here, valid padding is no padding as said in lecture.

In [0]:
def conv2d(input_mat, kernel_mat):
  #checking if the matrices are square
  try:
    if square(input_mat) == False:
      raise NotSquare("input_mat")
  except NotSquare as e:
    print(e.message)
    return []
  try:
    if square(kernel_mat) == False:
      raise NotSquare("kernel_mat")
  except NotSquare as e:
    print(e.message)
    return []
  
  #now check if input > kernel
  try:
    if len(input_mat) < len(kernel_mat) or len(input_mat[0]) < len(kernel_mat[0]):
      raise KernelTooLarge("ERROR: Kernel matrix is larger than the input matrix.")
  except KernelTooLarge as e:
    print(e.message)
    return []

  #no exceptions, so convolve
  else:
    #need to flip the kernel first
    out_size = len(input_mat[0]) - len(kernel_mat[0]) + 1
    output_mat = np.zeros((out_size, out_size))
    np.flip(kernel_mat,0)
    #now we can convolve the input matrix with the flipped kernal
    for x in range(out_size):
      row = np.zeros(out_size)
      for y in range(out_size):
        sum = 0
        for kx in range(len(kernel_mat)):
          for ky in range(len(kernel_mat)):
            sum += input_mat[kx+x][ky+y] * kernel_mat[kx][ky]
        row[y] = sum
      output_mat[x] = row
    return output_mat

Below are the TA-created test cases:

In [279]:
from scipy import signal

#test cases
input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  #if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
    #output_mat = []
  #else:
    #output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!

ERROR: Kernel matrix is larger than the input matrix.
[]
Correct output!



##Problem Two

Using only `numpy`, implement the function `maxpooling2d`. It takes as input `input_mat` and `s` and outputs `output_mat`. The variables `input_mat` and `output_mat` are **square** matrices and `s` is an integer. It should compute the maxpooling operation on **input_mat** using window of shape `s` times `s`.

This assumes a stride = s.

In [0]:
def maxpooling2d(input_mat, s):
  #checking if the matrix is square
  try:
    if square(input_mat) == False:
      raise NotSquare("input_mat")
  except NotSquare as e:
    print(e.message)
    return []
  
  #now check if input > kernel
  try:
    if len(input_mat) < s or len(input_mat[0]) < s:
      raise KernelTooLarge("ERROR: window size is larger than the input matrix.")
  except KernelTooLarge as e:
    print(e.message)
    return []

  #no exceptions, so maxpool
  else:
    out_size = len(input_mat[0]) - s 
    output_mat = np.zeros((out_size, out_size))

    #maxpool2d
    for x in range(out_size):
      row = np.zeros(out_size)
      for y in range(out_size):
        maximum = 0
        for kx in range(s):
          for ky in range(s):
            maximum = max(input_mat[kx+(x*s)][ky+(y*s)], maximum)
        row[y] = maximum
      output_mat[x] = row
    return output_mat

Below are the TA-created test cases:

I edited the 2nd test case, because the problem 2 description specifically said that the matrices would be square. This one was not, but had an expected matrix so I set that to `[]` instead like the expected output for the "kernel too large" error from the first problem.

I also added some newlines.

In [314]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

#expected_mat.append([[4, 2, 5],
# [2, 4, 5],
# [1, 3, 2]])
expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")


[[4. 2.]
 [2. 4.]]
Correct output!

ERROR:input_mat is not square.
[]
Correct output!



##Sources

Used to learn how to flip a numpy array:
https://www.geeksforgeeks.org/numpy-flip-python/

TA test case location: https://colab.research.google.com/drive/1MIoNq4_xglLesBF1kdWJelP2CmdPuYbv

I also referenced **Deep Learning with Python** Chapter 5 to learn about convolution and max pooling.

Convolution visualization: https://github.com/schneider128k/machine_learning_course/blob/master/slides/images/convolution_overview.gif

Max pooling visualization: https://github.com/schneider128k/machine_learning_course/blob/master/slides/images/maxpool_animation.gif