Problem 2:
Inside a colab notebook implement a **Python function multiply_matrices** that **takes as input a list of numpy arrays and outputs their product.** It should **raise a custom exception if there is a pair of incompatible matrices.** The exception message should **provide information about which pair of matrices is bad.** Make sure that you follow the style guide for Python. Also use simple markup for formatting your notebook and include a simple description of what your program does inside a text cell. You should also use some simple Latex commands, for instance, when explaining what it means for two matrices to be compatible.

Make this notebook editable (so the TAs can directly put comments in the notebook), obtain a sharable link, enter it in Webcourses, and also save this notebook to your GitHub repo inside the folder called HW_1.



---



##Function Explanation
The **multiply_matrices** function takes a list of numpy arrays as input. It then checks the dimensions.
If the list only has 1 matrix, I attempt to multiply it by itself.
If the list has 2+ arrays, I multiply them all together, in the order given, for 1 final product.

In [0]:
import numpy as np

class Error(Exception):
  """baseline for other errors"""

# multiplication error due to dimension
class MultError(Error):
  def __init__(self, message):
    self.message = "These cannot be multiplied due to dimension:\n" + message + "\n"

# empty list error
class EmptyError(Error):
  def __init__(self, message):
    self.message = message

# function to multiply matrices
def multiply_matrices(li):
  try:
    if len(li) == 0:
      raise EmptyError("Hold up, that list is totally empty!\n")
  except EmptyError as e:
    print(e.message)
  else:
    if(len(li)) == 1:
      li.append(li[0])
    for i in range(len(li)-1):
      try:
        if i == 0:
          a = li[i]
          b = li[i+1]
        else:
          a = lastProd
          b = li[i+1]
        if a.shape[1] != b.shape[0]:
          raise MultError(str(a) + "\n" + str(b))
      except MultError as e:
        print(e.message)
      else:
        lastProd = np.matmul(a, b)
        print("Product: \n" + str(lastProd))
        print()

##Multiplying the Matrices
The following example is a list of matrices that call be multiplied together (in the order given) to 1 single product matrix.

In [0]:
#input the list
li = []
li.append(np.full((1,2),2))
li.append(np.full((2,3),3))
li.append(np.full((3,4),4))
li.append(np.full((4,5),5))

#call function to test multiplication
multiply_matrices(li)

Product: 
[[12 12 12]]

Product: 
[[144 144 144 144]]

Product: 
[[2880 2880 2880 2880 2880]]



##Empty List Exception
We cannot multiply an empty list of matrices, so EmptyError is raised.

In [0]:
#empty list
li_empty = []
multiply_matrices(li_empty)

Hold up, that list is totally empty!



##MultError
When attempting to multiply matrices that are incompatible, a MultError is raised.

In [0]:
#row and column mismatch, can't multiply
li_mult_error = []
li_mult_error.append(np.full((2,2),2))
li_mult_error.append(np.full((3,4),3))

multiply_matrices(li_mult_error)

These cannot be multiplied due to dimension:
[[2 2]
 [2 2]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]



Two matrices are incompatible and thus cannot be multiplied when:
The **column number** of the first matrix does not equal the **row number** of the second matrix.
For the example above:

$\begin{pmatrix}2 & 2\\ 2 & 2 \end{pmatrix}$ has dimension (2,2)

$\begin{pmatrix}3 & 3 & 3 \\ 3 & 3 & 3 \\ 3 & 3 & 3\end{pmatrix}$ has dimension (3,3)

Because the columns of $\begin{pmatrix}2 & 2\\ 2 & 2 \end{pmatrix}$ and the rows of $\begin{pmatrix}3 & 3 & 3 & 3 \\ 3 & 3 & 3 & 3 \\ 3 & 3 & 3 & 3 \end{pmatrix}$
mismatch ($2\neq3$) they cannot be multiplied together.

and thus MultError is raised.


## Sources

Python and Numpy Tutorials - used to familiarize myself with Python and Numpy

https://colab.research.google.com/drive/1CdwvzRhFNIlhp1mWVWFXSXAsmRFWvASq

https://colab.research.google.com/drive/1oixeI3yWIKkjCyg7SVIV-1mXI3LUbCAN#scrollTo=W35e4f-b03r8

Exception handling in Python - used to learn how exceptions work

https://docs.python.org/2/tutorial/errors.html
