Problem 2:
Inside a colab notebook implement a **Python function multiply_matrices** that **takes as input a list of numpy arrays and outputs their product.** It should **raise a custom exception if there is a pair of incompatible matrices.** The exception message should **provide information about which pair of matrices is bad.** Make sure that you follow the style guide for Python. Also use simple markup for formatting your notebook and include a simple description of what your program does inside a text cell. You should also use some simple Latex commands, for instance, when explaining what it means for two matrices to be compatible.

Make this notebook editable (so the TAs can directly put comments in the notebook), obtain a sharable link, enter it in Webcourses, and also save this notebook to your GitHub repo inside the folder called HW_1.



---



In [0]:
import numpy as np

# multiplication error due to dimension
class MultError(Error):
  def __init__(self, message):
    self.message = "These cannot be multiplied due to dimension:\n" + message + "\n"

# empty list error
class EmptyError(Error):
  def __init__(self, message):
    self.message = message

# function to multiply matrices
def multiply_matrices(li):
  try:
    if len(li) == 0:
      raise EmptyError("Hold up, that list is totally empty!")
  except EmptyError as e:
    print(e.message)
  if(len(li)) == 1:
      li.append(li[0])
  for i in range(len(li) - 1):
    try:
      a = li[i]
      b = li[i+1]
      if a.shape[1] != b.shape[0]:
        raise MultError(str(a) + "\n" + str(b))
    except MultError as e:
      print(e.message)
    else:
        print("Product: \n" + str(np.matmul(a, b)))
        print()
    try:
      a = li[i+1]
      b = li[i]
      if a.shape[1] != b.shape[0]:
        raise MultError(str(a) + "\n" + str(b))
    except MultError as e:
      print(e.message)
    else:
        print("Product: \n" + str(np.matmul(a, b)))
        print()

In [219]:
#input the list
li = []
li.append(np.full((1,2),2))
li.append(np.full((2,3),3))
li.append(np.full((2,4),4))
li.append(np.full((4,5),5))

li_empty = []


#call function to test multiplication
multiply_matrices(li)
multiply_matrices(li_empty)

Product: 
[[12 12 12]]

These cannot be multiplied due to dimension:
[[3 3 3]
 [3 3 3]]
[[2 2]]

These cannot be multiplied due to dimension:
[[3 3 3]
 [3 3 3]]
[[4 4 4 4]
 [4 4 4 4]]

These cannot be multiplied due to dimension:
[[4 4 4 4]
 [4 4 4 4]]
[[3 3 3]
 [3 3 3]]

Product: 
[[80 80 80 80 80]
 [80 80 80 80 80]]

These cannot be multiplied due to dimension:
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[4 4 4 4]
 [4 4 4 4]]

Hold up, that list is totally empty!


### Explanation
The **multiply_matrices** function takes a list of numpy arrays as input. It then checks the dimensions.
If the list only has 1 matrix, I attempt to multiply it by itself.
If the list has 2+ arrays, I multiply them both forwards and backwards.
What I mean by that if I have 2 matrices A and B, I attempt to multiply AB and BA.

Two matrices are incompatible and thus cannot be multiplied when:
The column number of the first matrix does not equal the row number of the second matrix.

For example:

```
li.append(np.full((1,2),2))
li.append(np.full((2,3),3))
```

These first 2 matrices in the program will multiply because their dimensions are (1,2) and (2,3). However, switching the order that they're multiplied in will result in a MultError, because their dimensions will be (2,3) and (1,2).

The custom exceptions I've written are **MultError** and **EmptyError**:

**MultError** is raised when two matrices cannot be multiplied together. It prints the matrices that caused this, in the order in which they were being multiplied.

**EmptyError** is raised when the list input into the multiply_matrices function is empty. It displays a message saying that the list is empty.

### Sources

Python and Numpy Tutorials - used to familiarize myself with Python and Numpy

https://colab.research.google.com/drive/1CdwvzRhFNIlhp1mWVWFXSXAsmRFWvASq

https://colab.research.google.com/drive/1oixeI3yWIKkjCyg7SVIV-1mXI3LUbCAN#scrollTo=W35e4f-b03r8

Exception handling in Python - used to learn how exceptions work

https://docs.python.org/2/tutorial/errors.html
